import streamlit as st
import pandas as pd
import numpy as np
import time
import os
from datetime import datetime


# =========================================================
# PAGE CONFIGURATION
# =========================================================

st.set_page_config(
    page_title="Seafloor Magnetic Scanner",
    page_icon="🌊",
    layout="wide"
)


# =========================================================
# CUSTOM CSS
# =========================================================

st.markdown("""
<style>

.main-title {
    font-size: 32px;
    font-weight: 700;
    text-align: center;
    margin-bottom: 5px;
}

.subtitle {
    text-align: center;
    color: #9aa4b2;
    font-size: 16px;
    margin-bottom: 25px;
}

.alert-box {
    padding: 20px;
    border-radius: 12px;
    background-color: #3b1111;
    border: 2px solid #ff4b4b;
    text-align: center;
    margin: 15px 0;
}

.normal-box {
    padding: 20px;
    border-radius: 12px;
    background-color: #102817;
    border: 2px solid #21c354;
    text-align: center;
    margin: 15px 0;
}

.info-box {
    padding: 15px;
    border-radius: 10px;
    background-color: #10243a;
    border: 1px solid #2471a3;
    margin-top: 10px;
}

</style>
#MainMenu {visibility: hidden;}
footer {visibility: hidden;}
header {visibility: hidden;}
""", unsafe_allow_html=True)


# =========================================================
# SESSION STATE
# =========================================================

if "signals" not in st.session_state:
    st.session_state.signals = []

if "timestamps" not in st.session_state:
    st.session_state.timestamps = []

if "baseline" not in st.session_state:
    st.session_state.baseline = 0

if "anomalies" not in st.session_state:
    st.session_state.anomalies = 0

if "calibrating" not in st.session_state:
    st.session_state.calibrating = False

if "calibration_samples" not in st.session_state:
    st.session_state.calibration_samples = []

if "calibration_start" not in st.session_state:
    st.session_state.calibration_start = None

if "anomaly_active" not in st.session_state:
    st.session_state.anomaly_active = False

if "logging" not in st.session_state:
    st.session_state.logging = True

# =========================================================
# SIDEBAR
# =========================================================

st.sidebar.title("⚙️ Control Panel")

st.sidebar.success("🟢 LIVE HARDWARE MODE")

st.sidebar.info(
    "Dashboard is actively receiving real-time magnetic "
    "sensor data from the custom Arduino PI detector via USB Serial."
)


# ---------------- CALIBRATION BUTTON ----------------

if st.sidebar.button("🎯 Calibrate Baseline", use_container_width=True):

    st.session_state.calibrating = True

    st.session_state.calibration_samples = []

    st.session_state.calibration_start = time.time()


# ---------------- CSV LOGGING ----------------

st.session_state.logging = st.sidebar.checkbox(
    "💾 Enable CSV Logging",
    value=True
)


# ---------------- RESET BUTTON ----------------

if st.sidebar.button("🔄 Reset System", use_container_width=True):

    st.session_state.signals = []

    st.session_state.timestamps = []

    st.session_state.baseline = 0

    st.session_state.anomalies = 0

    st.session_state.calibrating = False

    st.session_state.calibration_samples = []

    st.session_state.calibration_start = None

    st.session_state.anomaly_active = False

    st.rerun()


# =========================================================
# HEADER
# =========================================================

st.markdown(
    '<div class="main-title">'
    '🌊 SEAFLOOR MAGNETIC ANOMALY DETECTION SYSTEM'
    '</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">'
    'Real-Time Magnetic Signal Monitoring & Mineral Detection'
    '</div>',
    unsafe_allow_html=True
)

# =========================================================
# LIVE HARDWARE SENSOR
# =========================================================
signal = st.session_state.baseline # Fallback
timestamp = datetime.now()

if os.path.exists("processed_data.csv"):
    try:
        # Read the noise-gated file generated by your Python script
        df_live = pd.read_csv("processed_data.csv")
        if not df_live.empty:
            # Grab the absolute newest reading from the Arduino
            signal = float(df_live["Signal"].iloc[-1])
    except Exception:
        pass # Ignore temporary errors if the file is mid-write


# =========================================================
# 5-SECOND DYNAMIC CALIBRATION
# =========================================================
if st.session_state.calibrating:
    st.session_state.calibration_samples.append(signal)
    
    elapsed = time.time() - st.session_state.calibration_start
    
    # Run calibration for 5 seconds to gather sufficient baseline data
    if elapsed >= 5.0:
        if len(st.session_state.calibration_samples) > 0:
            new_baseline = np.mean(st.session_state.calibration_samples)
            st.session_state.baseline = round(new_baseline, 2)
            
        st.session_state.calibrating = False
        st.session_state.calibration_start = None
        st.session_state.calibration_samples = []

# =========================================================
# ANOMALY DETECTION
# =========================================================

# Main detection threshold
threshold_high = st.session_state.baseline +10

# Lower threshold used to reset anomaly state
# This prevents one target from being counted multiple times.
threshold_low = st.session_state.baseline +5


anomaly = signal > threshold_high


# ---------------------------------------------------------
# COUNT ONLY ONE EVENT
# ---------------------------------------------------------

if anomaly and not st.session_state.anomaly_active:

    st.session_state.anomalies += 1

    st.session_state.anomaly_active = True


# ---------------------------------------------------------
# RESET AFTER SIGNAL RETURNS TO NORMAL
# ---------------------------------------------------------

if signal < threshold_low:

    st.session_state.anomaly_active = False


# =========================================================
# STORE SENSOR DATA
# =========================================================

st.session_state.signals.append(signal)

st.session_state.timestamps.append(timestamp)


# Keep only latest 100 readings
st.session_state.signals = (
    st.session_state.signals[-100:]
)

st.session_state.timestamps = (
    st.session_state.timestamps[-100:]
)


# =========================================================
# CSV LOGGING
# =========================================================

if st.session_state.logging:

    os.makedirs(
        "data",
        exist_ok=True
    )

    file_path = "data/session_log.csv"


    row = pd.DataFrame([{

        "timestamp": timestamp,

        "signal_strength": signal,

        "baseline": st.session_state.baseline,

        "threshold": threshold_high,

        "anomaly": anomaly

    }])


    if os.path.exists(file_path):

        row.to_csv(
            file_path,
            mode="a",
            header=False,
            index=False
        )

    else:

        row.to_csv(
            file_path,
            index=False
        )


# =========================================================
# TOP METRICS
# =========================================================

col1, col2, col3, col4 = st.columns(4)


col1.metric(
    "Sensor Status",
    "CONNECTED"
)


col2.metric(
    "Baseline",
    f"{st.session_state.baseline:.2f}"
)


col3.metric(
    "Current Signal",
    f"{signal:.2f}"
)


col4.metric(
    "Anomaly Events",
    st.session_state.anomalies
)


st.divider()


# =========================================================
# DETECTION STATUS
# =========================================================

if anomaly:

    st.markdown(
        """
        <div class="alert-box">

        <h2>🚨 ANOMALY DETECTED</h2>

        <p>
        Possible metallic target detected
        </p>

        </div>
        """,
        unsafe_allow_html=True
    )

else:

    st.markdown(
        """
        <div class="normal-box">

        <h2>🟢 NORMAL BACKGROUND</h2>

        <p>
        No significant magnetic anomaly detected
        </p>

        </div>
        """,
        unsafe_allow_html=True
    )


# =========================================================
# CALIBRATION STATUS
# =========================================================
if st.session_state.calibrating:
    elapsed = time.time() - st.session_state.calibration_start
    remaining = max(5.0 - elapsed, 0.0)
    progress = min(elapsed / 5.0, 1.0)
    
    st.warning(
        f"⏳ **Calibrating Baseline...** {remaining:.1f} seconds remaining.\n\n"
        f"Gathering environmental data. Keep the sensor completely still over plain sand."
    )
    st.progress(progress)


# =========================================================
# LIVE GRAPH
# =========================================================

st.subheader("📈 Real-Time Magnetic Signal")


if len(st.session_state.signals) > 1:
    
    # Get the current number of points on the graph
    n_points = len(st.session_state.signals)

    # Add the Baseline and Threshold as flat lines across the whole graph
    chart_data = pd.DataFrame({
        "Signal Strength": st.session_state.signals,
        "Baseline": [st.session_state.baseline] * n_points,
        "Trigger Threshold": [threshold_high] * n_points
    })

    st.line_chart(
        chart_data,
        height=400
    )

else:
    st.info(
        "Collecting sensor data..."
    )

# =========================================================
# ANALYTICS
# =========================================================

# FIXED: Prevent ZeroDivisionError crash if baseline is exactly 0.0
safe_baseline = st.session_state.baseline if st.session_state.baseline > 0 else 1.0

deviation = (
    (signal - st.session_state.baseline) / safe_baseline
) * 100


col1, col2, col3 = st.columns(3)

col1.metric(
    "Signal Deviation",
    f"{deviation:.1f}%"
)

col2.metric(
    "Detection Threshold",
    f"{threshold_high:.2f}"
)

col3.metric(
    "Samples Collected",
    len(st.session_state.signals)
)

# =========================================================
# FOOTER INFORMATION
# =========================================================

# FIXED: Safe max() in case the list was just cleared by the Reset button
peak_signal = max(st.session_state.signals) if st.session_state.signals else 0.0

st.caption(
    f"Peak Signal: {peak_signal:.2f}  |  "
    f"CSV Logging: "
    f"{'ON 🟢' if st.session_state.logging else 'OFF 🔴'}"
)

# =========================================================
# AUTO REFRESH
# =========================================================

time.sleep(0.2)

st.rerun()